### ISSUE TITLE
Adding size method to dataloaders

### ISSUE THREAD

**Issue by jaycehaoranwang** [lolzballs/mie429#1]
Hi Ben please add easily callable method to dataloaders so that I can call it and get the size of the data returned to me, or if I'm just missing how to do it please let me know lmao

**Comment by lolzballs** [comment]
What do you need the size for? It's not really easily accessible right now because everything is lazily-evaluated. If you really need it we can probably hard-code it for the dataset.

**Comment by jaycehaoranwang** [comment]
ohh I see, I only wanted it to calculate some metrics for show while training but I think I can actually make do without it for now all good
